export const ActionTypes = {
  GET_TODOS: "GET_TODOS",
  GET_POSTS: "GET_POSTS",
  GET_USERS: "GET_USERS",
  TOGGLE_TODO: "TOGGLE_TODO",
  ERROR_USERS: "ERROR_USERS",
  ERROR_TODOS: "ERROR_TODOS",
  ERROR_POSTS: "ERROR_POSTS",
  ADD_POST: "ADD_POST",
};
